### ISSUE TITLE
如何避免单纯的改变开关状态而不进行回调 #10

### ISSUE THREAD

**Issue by 1184104588** [zcweng/SwitchButton#12]
如标题

**Comment by captain991** [comment]
添加TAG，需要通过代码修改状态而不触发监听回调的时候添加一个TAG,改变玩状态后把TAG置空。在监听回掉中检测到TAG就不继续执行。举个例子
sc.setTag(“随便一个Object就行”);
sc.setChecked(isChecked);
sc.setTag(null);

public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
      if (buttonView.getTag() != null) {
          return;
      }
      ...你正常的逻辑
}

**Comment by MartinLi2015** [comment]
那么在RecyclerView中，View被重复利用时，还是会有问题吧

**Comment by captain991** [comment]
一样的，onBindViewHoler的时候也是加TAG把对应的item的开关置为JavaBean的选中字段的状态

**Comment by captain991** [comment]
@MartinLi2015 一样的，onBindViewHoler的时候也是加TAG把对应的item的开关置为JavaBean的选中字段的状态。而且其实用不到这个控件，Google官方有一个SwitchCompact，用法是差不多的
