### ISSUE TITLE
代码中设置了switchButton.setEnableEffect(false);还是能点击，点击还是有反应！我想实现不可点击状态

### ISSUE THREAD

**Issue by yecaler** [zcweng/SwitchButton#25]
代码中设置了switchButton.setEnableEffect(false);还是能点击，点击还是有反应！
我想实现不可点击状态如何设置？

**Comment by supperyan** [comment]
help

**Comment by supperyan** [comment]
已解决！
gasOpen.setEnabled(false);
这样设置会起效果。
