### ISSUE TITLE
setChecked()会触发OnCheckedChangeListener监听器

### ISSUE THREAD

**Issue by AlexMofer** [zcweng/SwitchButton#3]
```java
@Override
    public void setChecked(boolean checked) {
        if(checked == isChecked()){
            postInvalidate();
            return;
        }
        toggle(enableEffect, false);
    }
```
当状态不相同时，会进入void toggle(boolean animate, boolean broadcast)，虽然不进行监听播报，但是如果setEnableEffect(boolean enable)属于开启状态时，会启动开关的动画。但是在动画设置的动画动画监听器会在动画结束时播报改变事件，所以在动画结束时会进行一次void onCheckedChanged(SwitchButton view, boolean isChecked)事件播报。
所以当setEnableEffect(true)时，进行setChecked(!isChecked())必然会触发OnCheckedChangeListener监听器（并非立即触发，而是在动画结束以后触发的）。
如果调用toggle()会不会出现触发两次监听器（动画前一次，动画后一次）？（没有测试，未使用toggle()方法）
目前解决方案是在setChecked(boolean)之前先setEnableEffect(false)，完成后再setEnableEffect(true)回去，期望作者早日修复，谢谢。

**Comment by zcweng** [comment]
好的，

**Comment by zcweng** [comment]
1，toggle不会触发2次回调OnCheckedChangeListener哈。（详细原因请看源码，）toggle方法被调用是时候，如果启用动画效果，会开始执行动画，只有动画结束时回调OnCheckedChangeListener。
2，你说在开启动画条件下调用setChecked会触发OnCheckedChangeListener，是正常设计哈。

**Comment by zcweng** [comment]
如果你希望控件初始状态是开启，你可以在获取到数据后，先设置setOnCheckedChangeListener(null)。然后setChecked(true),再次setOnCheckedChangeListener(your listener)；

**Comment by AlexMofer** [comment]
因为你的控件是在动画结束以后回调监听器，我是按照官方的Switch控件的思路想的（官方Switch控件setChecked(true)后，状态改变会立马回调，可参见源码，然后才执行相关状态变化的动画），所以就觉得有点问题了，不过你这样设计那也无可厚非。
但是要设置初始状态为开启的话，按照你的思路：
```java
setOnCheckedChangeListener(null)
setChecked(true)
setOnCheckedChangeListener(your listener)
```
这样铁定会导致监听器被触发的，虽然在setChecked(true)之前将监听器置空了，但是setChecked(true)会触发动画，此时动画执行，但是紧接着又将监听器设置回去，当动画结束以后，监听器就又被调用了。亲测如此。
目前我的解决方案：
```java
sbFunction.setEnableEffect(false);
sbFunction.setChecked(true);
sbFunction.setEnableEffect(true);
```
这样不用管监听器，不管你是否设置，其不会被触发到。
具体可参考你的控件的源码：
```java
@Override
public void setChecked(boolean checked) {
    if(checked == isChecked()){
        postInvalidate();
        return;
    }
    toggle(enableEffect, false);
}
```
因为设置了setEnableEffect(false)，所以执行的是内部的private方法toggle(false, false);此时既不执行动画也不播报监听就将状态改变过去了。

**Comment by wawo00** [comment]
可以修改下源码，追加一个标志位

![Image](https://github.com/user-attachments/assets/540ccac0-d94c-4100-a101-0ca293d2402c)

![Image](https://github.com/user-attachments/assets/688046d5-5e45-41a8-a4dd-8d6f3a565501)

我看源代码中作者好像也想避免这样的事情出现，但是回调是在动画结束时，状态改为ANIMATE_STATE_SWITCH时触发的，看上去不是很理想
